### ISSUE TITLE
Cannot install slcad_transform_0.93.1.hotfix.2 on blender 2.93.5 on linux mint  20.1

### ISSUE THREAD

**Issue by fredoonearth** [s-leger/blender_cad_transforms#69]
when i install slcad_transform_0.93.1.hotfix.2, enabling addon, error message appear:

**Comment by fredoonearth** [comment]
after installing addon, when enabling it , error message appear:

Python: Traceback (most recent call last):
  File "/app/blender/2.93/scripts/startup/bl_ui/space_view3d.py", line 51, in draw
    self.draw_tool_settings(context)
  File "/app/blender/2.93/scripts/startup/bl_ui/space_view3d.py", line 68, in draw_tool_settings
    tool = ToolSelectPanelHelper.draw_active_tool_header(
  File "/app/blender/2.93/scripts/startup/bl_ui/space_toolsystem_common.py", line 782, in draw_active_tool_header
    draw_settings(context, layout, tool)
  File "/home/fredo/.var/app/org.blender.Blender/config/blender/2.93/scripts/addons/slcad_transform/slcad_transform.py", line 1041, in draw_settings
    row = layout
KeyError: 'bpy_prop_collection[key]: key "slcad_transform" not found'

location: <unknown location>:-1
